
package com.babelgroup.gede.util.afirma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DSSSignature", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface DSSSignature {


    /**
     * 
     * @param dssXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "signReturn", partName = "signReturn")
    public String sign(
        @WebParam(name = "dssXML", partName = "dssXML")
        String dssXML);

}
