
package com.babelgroup.gede.util.afirma;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "DSSSignatureService", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema")
public class DSSSignatureService extends Service {

	public static final String DSSSIGNATURESERVICE_QNAME = "urn:oasis:names:tc:dss:1.0:core:schema";

	public static final URL DSSSIGNATURESERVICE_WSDL_LOCATION = null;

	public static final QName DSSSIGNATURESERVICEQNAMEQ = new QName(DSSSIGNATURESERVICE_QNAME, "DSSSignatureService");

	public DSSSignatureService(URL wsdlLocation) {
		super(wsdlLocation, DSSSIGNATURESERVICEQNAMEQ);
	}

	public DSSSignatureService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, DSSSIGNATURESERVICEQNAMEQ, features);
	}

	public DSSSignatureService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DSSSignatureService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns DSSSignature
	 */
	@WebEndpoint(name = "DSSAfirmaSign")
	public DSSSignature getDSSAfirmaSign() {
		return super.getPort(new QName(DSSSIGNATURESERVICE_QNAME, "DSSAfirmaSign"), DSSSignature.class);
	}

	/**
	 * 
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns DSSSignature
	 */
	@WebEndpoint(name = "DSSAfirmaSign")
	public DSSSignature getDSSAfirmaSign(WebServiceFeature... features) {
		return super.getPort(new QName(DSSSIGNATURESERVICE_QNAME, "DSSAfirmaSign"), DSSSignature.class, features);
	}

}
